In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mplfinance as mpf

In [3]:
crypto = pd.read_csv('/Users/jonas/Documents/GitHub/ZHAW/Semester 5/MLDM/Hackathon/data/crypto_time_series.csv')

# separate after "coin"
df = crypto[crypto['coin'] == 'BTC'].copy()
df['date'] = pd.to_datetime(df['date'])

,date,open,high,low,close,volume,market_cap,coin
0,2018-08-14,6287.66,6287.94,5971.05,6199.71,5.301700e+09,1.081991e+11,BTC
1,2018-08-13,6341.36,6537.05,6225.72,6297.57,4.083980e+09,1.091115e+11,BTC
2,2018-08-12,6283.65,6409.85,6237.50,6322.69,5.665250e+09,1.081065e+11,BTC
3,2018-08-11,6185.79,6455.74,6109.03,6295.73,4.047850e+09,1.064095e+11,BTC
4,2018-08-10,6571.42,6591.26,6124.52,6184.71,4.528680e+09,1.130288e+11,BTC
...,...,...,...,...,...,...,...,...
1930,2013-05-02,116.38,125.60,92.28,105.21,NaN,1.292190e+09,BTC
1931,2013-05-01,139.00,139.89,107.72,116.99,NaN,1.542820e+09,BTC
1932,2013-04-30,144.00,146.93,134.05,139.00,NaN,1.597780e+09,BTC
1933,2013-04-29,134.44,147.49,134.00,144.54,NaN,1.491160e+09,BTC
1934,2013-04-28,135.30,135.98,132.10,134.21,NaN,1.500520e+09,BTC

In [10]:
# Calculate the daily average price
btc = df.copy()
btc['avg_price'] = (df['open'] + df['high'] + df['low'] + df['close']) / 4
btc.drop('low', axis=1, inplace=True)
btc.drop('open', axis=1, inplace=True)
btc.drop('high', axis=1, inplace=True)
btc.drop('close', axis=1, inplace=True)
btc.drop('market_cap', axis=1, inplace=True)
btc.drop('coin', axis=1, inplace=True)
btc

           date        volume  avg_price
0    2018-08-14  5.301700e+09  6186.5900
1    2018-08-13  4.083980e+09  6350.4250
2    2018-08-12  5.665250e+09  6313.4225
3    2018-08-11  4.047850e+09  6261.5725
4    2018-08-10  4.528680e+09  6367.9775
...         ...           ...        ...
1930 2013-05-02           NaN   109.8675
1931 2013-05-01           NaN   125.9000
1932 2013-04-30           NaN   140.9950
1933 2013-04-29           NaN   140.1175
1934 2013-04-28           NaN   134.3975

[1935 rows x 3 columns]

In [16]:
# calculate the x daily returns
x_days = 30
btc[f'return_{x_days}d'] = btc['avg_price'].pct_change(x_days) * 100
btc.dropna(inplace=True)
btc

           date        volume  avg_price  return_7d  return_30d
78   2018-05-28  5.040600e+09  7256.8100  -0.047189   14.741471
79   2018-05-27  4.056520e+09  7345.7500  -0.043531   21.347956
80   2018-05-26  4.051540e+09  7446.6600  -0.019314   23.595709
81   2018-05-25  4.867830e+09  7531.0575   0.002329   23.084752
82   2018-05-24  6.049220e+09  7554.5500   0.011645   22.187291
...         ...           ...        ...        ...         ...
1687 2013-12-31  2.089730e+07   753.2700  -0.143094   -8.182874
1688 2013-12-30  2.070770e+07   751.0800  -0.211913  -10.099287
1689 2013-12-29  1.901130e+07   734.0375  -0.184176  -10.831749
1690 2013-12-28  3.250580e+07   729.5550  -0.127316  -10.883433
1691 2013-12-27  4.686270e+07   747.3650  -0.078703   -6.169158

[1447 rows x 5 columns]